config/routes.rb
RecordYourPomodori3::Application.routes.draw do
  resources :users do
    resources :monthly_reports, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :daily_reports, only: [:new, :create, :edit, :update, :destroy]
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  get 'static_pages/index'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  root 'static_pages#index'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide :title, 'About' %>

<div class="container">
  <div class="page-header">
    <h2>このサイトについて</h2>
  </div>

  <h3>Record Your Pomodori</h3>

  <p>「Record Your Pomodori」は、ポモドーロ・テクニックのレコード（日々の実績）を記録するためのウェブアプリケーションです。</p>

  <p>ポモドーロ・テクニックとは、タスク管理の技法のことです。何か作業をするときには、キッチンタイマーを25分にセットして、その25分間はそのことだけに集中します。25分が過ぎたら5分間休憩します。本式のポモドーロ・テクニックでは、この25分間と5分間の1セットを「ポモドーリ」という単位で数えるそうです。ポモドーロ・テクニックでは、1日にこなしたポモドーリの数などを積極的に記録して、後から分析することが推奨されています。</p>

  <p>「Record Your Pomodori」では、日ごとのポモドーリと完了したタスクの数を記録することができます。</p>

</div>

app/views/static_pages/contact.html.erb
<% provide :title, 'Contact' %>

<div class="container">
  <div class="page-header">
    <h2>お問い合わせ</h2>
  </div>

  <h3>連絡先</h3>

  <p>
    お問い合わせは、下記Twitterアカウント宛てにメッセージをいただくか、ブログのコンタクトフォームからご連絡をいただきますようお願いします。
  </p>

  <dl>
    <dt><%= fa_icon "twitter", text: "Twitter" %></dt>
    <dd><%= link_to '@succi0303', 'https://twitter.com/succi0303', { target: '_blank' } %></dd>
    <dt><%= fa_icon "rss-square", text: "Blog" %></dt>
    <dd><%= link_to 'prime factor', 'http://www.succi.jp/blog/', { target: '_blank' } %></dd>
  </dl>

  <h3>ソースコード</h3>

  <p>
    本ウェブサイトのソースコードはGithubで公開しています。ご興味を持っていただいた方は下記のGithubリポジトリを参照ください。
  </p>

  <dl>
    <dt><%= fa_icon "github", text: "Github" %></dt>
    <dd><%= link_to 'succi0303/record_your_pomodori3',
      'https://github.com/succi0303/record_your_pomodori3',
      { target: '_blank' } %></dd>
  </dl>
</div>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Record Your Pomodori</h1>
    <p>ポモドーロの実施状況（ポモドーロ実施数、タスク完了数）を記録して<br />
      月ごとの合計・平均を確認できます。</p>
    <p><%= fa_icon 'cutlery' %></p>
    <p><%= link_to 'ユーザー登録 »', new_user_path,
      class: 'btn btn-primary btn-lg' %></p>
  </div>

  <div class="notes">
    <p>** 作成者自身のプログラム学習を目的に作成しているアプリケーションです **<br>
      ** 内容は随時変更する可能性が有りますのでご注意ください **</p>
  </div>
</div>