config/routes.rb
RecordYourPomodori3::Application.routes.draw do
  resources :users do
    resources :monthly_reports, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :daily_reports, only: [:new, :create, :edit, :update, :destroy]
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  get 'static_pages/index'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  root 'static_pages#index'

end

app/views/layouts/_footer.html.erb
<div class="container">
  <p>
    Copyrights &copy; <%= link_to 'prime factor', 'http://www.succi.jp/blog/',
      {target: '_blank'} %>,
    2014 All Rights Reserved.
  </p>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Record Your Pomodori', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', about_path %></li>
<li><%= link_to 'Contact', contact_path %></li>
<% if signed_in? %>
  <li class="dropdown">
    <a class="dropdown-toggle" href="#" data-toggle="dropdown">Account <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Profile', current_user %></li>
      <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
      <li class="divider"></li>
      <li><%= link_to 'Sign out', signout_path, method: 'delete' %></li>
    </ul>
  </li>
<% else %>
  <li><%= link_to 'Sign in', signin_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Record Your Pomodori3" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href='http://fonts.googleapis.com/css?family=Elsie:900' rel='stylesheet' type='text/css'>

    <link href="//netdna.bootstrapcdn.com/bootswatch/3.1.1/simplex/bootstrap.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= yield :head %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>

    <footer class="site-footer">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>